name: tii-px4-sitl

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  pull_request_target:
    branches: [ master ]

jobs:
  tii-px4-sitl:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:

      # checkout merge branch for the forked PRs instead of PR base branch
      - name: PR checkout for px4-firmware
        uses: actions/checkout@v2
        if: github.event_name == 'pull_request_target'
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/merge
          token: ${{ secrets.GH_REPO_TOKEN }}
          persist-credentials: false
          path: px4-firmware
          submodules: recursive
          fetch-depth: 0

      # default checkout for local PRs and pushes
      - name: checkout for px4-firmware
        uses: actions/checkout@v2
        if: github.event_name == 'push' || github.event_name == 'pull_request'
        with:
          token: ${{ secrets.GH_REPO_TOKEN }}
          path: px4-firmware
          submodules: recursive
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host

      - name: Run sitl build
        run: |
          set -eux
          mkdir bin
          cd px4-firmware
          ./build_sitl.sh ../bin/
          ls ../bin/

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/tiiuae/tii-px4-sitl
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=sha
            type=raw,value=latest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build tii-px4-sitl image and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./px4-firmware/packaging/Dockerfile.sitl
          pull: true
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - uses: jfrog/setup-jfrog-cli@v2
        if: github.event_name == 'push'
        env:
          JF_ARTIFACTORY_1: ${{ secrets.ARTIFACTORY_TOKEN }}

      - name: Upload to Artifactory (px4-sitl)
        env:
          ARTIFACTORY_GEN_REPO: gen-public-local
          BUILD_NAME: px4-sitl
          CI: true
        if: github.event_name == 'push'
        run: |
          set -exu
          jfrog rt ping
          pkg=$(find bin -name 'px4_sitl_build*.tar.gz')
          pkg_name=$(basename $pkg)
          jfrog rt u --target-props COMMIT="$GITHUB_SHA" \
                     --build-name "$BUILD_NAME" \
                     --build-number "$GITHUB_SHA" \
                     "$pkg" \
                     "$ARTIFACTORY_GEN_REPO/builds/px4-firmware/sitl/$pkg_name"
          jfrog rt build-publish "$BUILD_NAME" "$GITHUB_SHA"
          jfrog rt bpr "$BUILD_NAME" "$GITHUB_SHA" "$ARTIFACTORY_GEN_REPO" \
                       --status dev \
                       --comment "development build"
          jfrog rt cp --flat \
                      "$ARTIFACTORY_GEN_REPO/builds/px4-firmware/sitl/$pkg_name" \
                      "$ARTIFACTORY_GEN_REPO/builds/px4-firmware/sitl/latest/px4_sitl_build.tar.gz"

      - name: Upload to Artifactory (px4-gazebo-data)
        env:
          ARTIFACTORY_GEN_REPO: gen-public-local
          BUILD_NAME: gazebo-data
          CI: true
        if: github.event_name == 'push'
        run: |
          set -exu
          jfrog rt ping
          pkg=$(find bin -name 'px4_gazebo_data*.tar.gz')
          pkg_name=$(basename $pkg)
          jfrog rt u --target-props COMMIT="$GITHUB_SHA" \
                     --build-name "$BUILD_NAME" \
                     --build-number "$GITHUB_SHA" \
                     "$pkg" \
                     "$ARTIFACTORY_GEN_REPO/builds/gazebo-data/$pkg_name"
          jfrog rt build-publish "$BUILD_NAME" "$GITHUB_SHA"
          jfrog rt bpr "$BUILD_NAME" "$GITHUB_SHA" "$ARTIFACTORY_GEN_REPO" \
                       --status dev \
                       --comment "development build"
          jfrog rt cp --flat \
                      "$ARTIFACTORY_GEN_REPO/builds/gazebo-data/$pkg_name" \
                      "$ARTIFACTORY_GEN_REPO/builds/gazebo-data/latest/px4_gazebo_data.tar.gz"
